# Generated by Django 3.0.7 on 2020-07-08 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AUTH', '0002_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
