# Generated by Django 3.0.7 on 2020-07-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTH', '0003_delete_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='https://img.pngio.com/profile-icon-png-image-free-download-searchpngcom-profile-icon-png-673_673.png', upload_to=''),
        ),
    ]
